apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rate-limiter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-rate-limiter
  template:
    metadata:
      labels:
        app: api-rate-limiter
    spec:
      containers:
      - name: api-rate-limiter
        image: suryabeeraka/api-rate-limiter:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-rate-limiter
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080